### ISSUE TITLE
English translation?

### ISSUE THREAD

**Issue by gluckgluckwasserbauch** [odrinari/Linux-screen-lock-with-MiBand-and-other-bluetooth-watches#3]
I'm super grateful for your project, it's exactly what I've been looking for. Thank you a lot!

Sadly, besides not being able to get it to work (running the .deb in an Ubuntu-Distrobox on Fedora, see the other issue) I can't speak russian/ read the cyrilic alphabet too well.

Would you be able to translate it?

**Comment by odrinari** [comment]
Hello, thank you again!

Yes, of course I would be able translate everything on English

Also I will let you know

**Comment by odrinari** [comment]
Hello again! @zewonex 

I translated the interface, so now you can use it

Hope it will help!
